server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:recipesdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#enabling the H2 console
  h2:
    console:
      enabled: true

secret: jwtsecrettoken

auth:
  un: admin

token:
  validity: 900000
